# Copyright (c) NetworkFusion, .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will build the solution and release a nuget.

name: Build nanoFramework lib and release nuget #TODO, handle releases!

on: [push, pull_request]

defaults:
  run:
    shell: pwsh

jobs:
  build-app:
    name: Build App using CI
    timeout-minutes: 15
    runs-on: windows-latest
    env:
      solution: 'nanoFramework.HelloWorld.sln'
      buildConfiguration: 'Release'

    steps:
      - uses: networkfusion/nanobuild@v1.6
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1

      - name: Install NuGet client
        uses: nuget/setup-nuget@v1

      - name: Restore nugets
        run: nuget restore ${{ env.solution }} -ConfigFile NuGet.Config
        
      - name: Build App
        run: msbuild ${{ env.solution }} /p:Configuration=${{ env.buildConfiguration }}
